###
//get home view
GET localhost/
###

###
GET localhost/users
###

###
POST localhost/users
Content-Type: application/x-www-form-urlencoded

user = %7B%22id%22%3A0%2C%22name%22%3A%22Mikita%22%2C%22email%22%3A%22retdarkw%40gmail.com%22%7D
###





